project_name: asos_movie_analysis
project_home_dir: C:\\Users\\jassm\\PycharmProjects\\pyspark-asos
spark:
  master: local[*]
  cores: 1
  mode: overwrite
Database:
  db1_server_name: 0.0.0.0
  db1_port: 0000
  db1_user_name: user
  db1_passwd: passwdDoNotShare
FileSystem:
  input:
    movies:  \\resources\\input\\movies.dat
    ratings:  \\resources\\input\\ratings.dat
    users:  \\resources\\input\\users.dat
  output:
    movies_avg_rating:  \\resources\\output\\movies_avg_rating_by_user
    movies_under_genre:  \\resources\\output\\total_movies_under_genre
    movies_top_hundred:  \\resources\\output\\top_hundred_movies